# Generated by Django 4.2.4 on 2023-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='date_when_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
