# Generated by Django 4.2.4 on 2023-09-07 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userverification_date_when_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
